#
#  docker-compose file supporting a docker stack comprised of a 
#  BaRS consumer simulator (provider test suite) instance 
#
version: "3"
services:
  tkw_bars_consumer_simulator:
    network_mode : "host"
    volumes:
        # <host path to mount> : <mount point within docker>
        # external configuration directory - can be disabled and the internal one defined in the "internal" external properties file used
        - '${TKWROOT}/config/FHIR_BaRS/external_configs:/home/service/TKW/config/FHIR_BaRS/external_configs'
        # Access token file location for the remote terminology server - an be disabled which will disable the use of the Terminology server - also need to disable any refs in the External Properties file
        - '${TKWROOT}/config/FHIR_BaRS/TerminologyServerLoginDetails:/home/service/access_token'
        # auto_tests folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/auto_tests:/home/service/TKW/config/FHIR_BaRS/autotest_config/auto_tests
        # endpoint_configs folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/endpoint_configs:/home/service/TKW/config/FHIR_BaRS/autotest_config/endpoint_configs
        # autotest logs folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/autotest_logs:/home/service/TKW/config/FHIR_BaRS/autotest_config/autotest_logs
    environment:
      - TZ=Europe/London
    image: nhsdigitalmait/tkw_bars_consumer_simulator:0.6.1
