version: '2.0'
services:
    tkw_bars_provider_simulator:
        ports:
            - '4434:4434'
        volumes:
            - '${TKWROOT}/config/FHIR_BaRS:/home/service/data'
        image: 'nhsdigitalmait/tkw_bars_provider_simulator:0.1'
