#
#  docker-compose file supporting a docker stack comprised of a 
#  BaRS consumer simulator (provider test suite) instance 
#
version: "3"
services:
  tkw_bars_consumer_simulator:
    image: nhsdigitalmait/tkw_bars_consumer_simulator:0.1

    environment:
      - TZ=Europe/London

    network_mode : "host"

    volumes:
        # <host path to mount> : <mount point within docker>
        # auto_tests folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/auto_tests:/home/service/TKW/config/FHIR_BaRS/autotest_config/auto_tests
        # endpoint_configs folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/endpoint_configs:/home/service/TKW/config/FHIR_BaRS/autotest_config/endpoint_configs
        # autotest logs folder
        - ${TKWROOT}/config/FHIR_BaRS/autotest_config/autotest_logs:/home/service/TKW/config/FHIR_BaRS/autotest_config/autotest_logs
        # external configuration directory
        #- ${TKWROOT}/config/FHIR_BaRS/external_configs:/home/service/TKW/config/FHIR_BaRS/external_configs
